### ISSUE TITLE
Menú Inicio

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-estarbax#2]
No habéis realizado el menú inicio cuya entrega estaba planificada para el día 20 de marzo.

**Comment by Eloy-Isidro** [comment]
Perdonanos por no haberte respondido antes, pero no habíamos visto este issue. En cuanto al menú, no nos habíamos dado cuenta de que había que entregarlo para el 20, ha sido un despiste por nuestra parte. El menú ya está listo, de ahora en adelante estaremos más pendientes de GitHub y las entregas. Disculpa las molestias.
