### ISSUE TITLE
Librerías no estándar

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-estarbax#3]
Estáis usando la librería [conio.h](https://es.wikipedia.org/wiki/Conio.h)
https://github.com/aigora/twE105_1920-estarbax/blob/476c82470952ab1e6ad0b1715118d413f5a5752e/MOVIMIENTOO.c#L2
Se trata de una libería no estándar, específica de sistemas MS-DOS. Eso implica que vuestro código no será portable (no se podrá instalar en otro tipo de sistemas operativos). 
Salvo que sea imprescindible para vuestro programa, debéis evitar el uso de esta librería y otras específicas de un sistema operativo.

**Comment by Eloy-Isidro** [comment]
No creo que la utilicemos, solo estábamos haciendo pruebas
