### ISSUE TITLE
Generar mapa de forma más sistemática

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-estarbax#5]
La forma en la que generáis el mapa...
https://github.com/aigora/twE105_1920-estarbax/blob/476c82470952ab1e6ad0b1715118d413f5a5752e/el%20mapa.c#L9
... es artesanal, vais posición a posición. ¿Que pasaría si cambian las dimensiones? 
Debéis pensar en generarlo de una forma más sistemática.

**Comment by Eloy-Isidro** [comment]
Hemos mejorado la forma de cargar el mapa; almacenándolos en ficheros
