### ISSUE TITLE
Ficheros y estructuras

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-estarbax#6]
No olvidéis que tenéis que utilizar ficheros y vectores de estructuras en el código.
Por ejemplo, podéis usar ficheros para almacenar diferentes mapas y para registrar los avances de los diferentes jugadores.

**Comment by Eloy-Isidro** [comment]
¿Cómo se utilizarían los ficheros para almacenar mapas?

**Comment by oscarperpinan** [comment]
Escribid el contenido de una matriz (por ejemplo) en un fichero usando fprintf.
Buscad en los repositorios de los otros equipos. Hay algún trabajo que está haciendo algo similar. También hay ejemplos en los del año pasado.
